elasticpath/js-sdk

src/types/rule-promotions.ts
* ### Feature
- update the RulePromotionBase type to support new fields: `priority` and `stackable`
=> [MT-16706] Update RulePromotionBase type

src/endpoints/custom-relationships.js, src/types/custom-relationships.d.ts
* ### Fix
BREAKING CHANGE: Fixed custom relationship endpoint as the API endpoint URLs were updated
* Fix is part of https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/paragon/team/-/issues/379
=> Fix: Custom relationship endpoints

src/index.d.ts
* ### Feat
- Expose all export types of `pcm-custom-relationship.ts` file
=> Feat: Export pcm custom relationship endpoint types

README.md
=> feat: expose pcm-custom-relationships types

src/endpoints/pcm-custom-relationship.js, src/types/pcm-custom-relationship.ts
* ### Feature
- Added `Limit` and `Offset` methods to `PcmCustomRelationshipEndpoint` class
=> feat: added limit and offset methods to pcm-custom-relationship class

.github/workflows/main.yml
chore: bump EnricoMi/publish-unit-test-result-action version
=> chore: bump EnricoMi/publish-unit-test-result-action version

src/types/custom-apis.ts
=> chore: Revert "feat(custom apis): adds missing properties to custom apis"

src/types/mli-locations.d.ts
* ### Fix
Fixes a bug
Added slug, made address and geolocation optional
* Fixes #
=> fix: Location types in Multi-location inventory

README.md
* ### Feature
- release optional description field
=> feat!: release optional description field

src/endpoints/mli-locations.js, src/types/mli-locations.d.ts
* ### Fix
Fixes a bug
Fixed the create location endpoint to include the ID in the body instead of in the attributes.
* Fixes #
=> fix: Multi-location inventory update location endpoint

src/endpoints/multi-location-inventories.js, src/types/multi-location-inventories.d.ts
* ### Feature
Added an Update endpoint for Multi-location Inventory + interfaces refactoring
* Fixes #
=> feat: added Update endpoint for MLI, interface updates

README.md
* ### Feature
- actually release the change this time
*A brief description of the goals of the pull request.*
* Fixes #
=> feat: release optional promotin source type in order

src/endpoints/rule-promotions.js, src/types/rule-promotions.ts
* ### Feature
- add new end point in rule promotions for managing export for bulk codes 
- [[MR-2792] Managing export for bulk codes](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/2792)
=> add new endpoint for exporting bulk codes

src/endpoints/rule-promotions.js
* ### Fix
Fixes a bug
- fix rule promotions jobs endpoint
* Fixes #
=> fix: rule promotions jobs endpoint

src/endpoints/rule-promotions.js, src/types/rule-promotions.ts
* ### Feature
- add new endpoint to cancel promotion codes job
- [[MR-2846] Improvement: code generation form](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/2846)
=> feat: add cancel jobs endpoint in rule promotions

src/endpoints/user-authentication-password-profile.js, src/types/user-authentication-password-profile.d.ts, test/unit/user-authentication-password-profile.ts
* ### Fix
Fixes a bug
Header was not being passed on Update requests.
=> !fix: supply accountManagementAuthenticationToken on update requests

src/endpoints/custom-api-role-policies.js, src/index.d.ts, src/index.js, src/types/custom-api-role-policies.ts
* ### Feature
- create new custom api role policies endpoints
- [[MR-2883] Support custom api role policies
](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/2883)
=> feat: create new custom api role policies endpoints

src/types/rule-promotions.ts
* ### Feature
- add override stacking type in RulePromotionBase
- [[MR-2900] Override stacking promotion](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/2900)
=> feat: add override stacking type

test/utils/helpers.ts
* ### Test
Adding missing or correcting existing tests
- fix filter test
=> fix: fix filter test

README.md
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
Documentation only changes
* ### Style
Changes that **do not** affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
* ### Refactor
A code change that neither fixes a bug nor adds a feature
* ### Performance
A code change that improves performance
* ### Test
Adding missing or correcting existing tests
* ### Chore
Changes to the build process or auxiliary tools and libraries such as documentation generation  
*A brief description of the goals of the pull request.*
* Fixes #
=> fix: release support top level and with nested or in filter
