elasticpath/js-sdk

src/endpoints/custom-relationships.js, src/index.d.ts, src/index.js, src/types/custom-relationships.d.ts
* ### Feature
- Added `CustomRelationships` endpoint implementation and type files
Related to: https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/paragon/team/-/issues/368
=> feat: Add custom relationships endpoint and type

src/endpoints/pcm-custom-relationship.js, src/endpoints/pcm.js, src/types/pcm-custom-relationship.ts, src/types/pcm.d.ts
* ### Feature
- Add `PcmCustomRelationshipEndpoint` class and use it as a member of the `PCM` endpoint class
As part of the newly added class, the following endpoint methods were added:
- Add endpoint method for attaching a custom relationship to a product (`AttachCustomRelationship`)
- Add endpoint for detaching a custom relationship from a product (`DetachCustomRelationship`)
- Add endpoint for fetching a product's attached custom relationships (`All`)
- Add endpoint for associating a product to another product under a custom relationship (`AssociateProductsToCustomRelationship`)
- Add endpoint for dissociating a product from another product under a custom relationship (`DissociateProductsFromCustomRelationship`)
- Add endpoint for fetching product IDs of a product's custom relationship …
=> feat: PCM Custom Relationship endpoint

src/types/pcm-custom-relationship.ts
* ### Fix
- Fixed return type of AttachCustomRelationshipToProduct method to use the `Resource<CustomRelationship>` interface instead of `CustomRelationshipsListResponse`
=> fix: return type of AttachCustomRelationshipToProduct method

src/types/rule-promotions.ts
* ### Feature
- add `RulePromotionFilter` type to address type issue in [[MR-2539] Feature: Add search functionality on the promotions page](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/2539) 
- [[MR-2539] Feature: Add search functionality on the promotions page](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/2539)
=> feat: add RulePromotionFilter type

src/types/custom-apis.ts
* ### Feature
Adds:
- `allow_upserts` to `CustomApiBase`
- `use_as_url_slug` to `CustomApiFieldBase`
- `immutable` to all validations
- `unique` and `unique_case_insensitivity` to `string` validation
BREAKING CHANGE: adds a required  `allow_upserts` to `CustomApiBase` and a required `use_as_url_slug` to CustomApiFieldBase
=> feat(custom apis): adds missing properties to custom apis

src/types/rule-promotions.ts
* ### Feature
- update `description` restriction to be optional
[[MT-17854] Make description field optional](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/2576) depends on the this PR
=> feat: make description field optional

src/types/core.d.ts, src/types/pcm-custom-relationship.ts, src/types/pcm.d.ts
* ### Feature
BREAKING CHANGE:
- Updated `AttachCustomRelationship` method second argument to be an array
- Removed `PcmRelatedProductResponse` from . Instead, it was renamed to `SimpleResourcePageResponse` and moved to the `core.d.ts` file. Updated endpoint method usages.
- Updated `PcmProduct` and `PcmProductRelationships ` types to include new custom_relationship fields
- Fixed `ProductAssociationResponse ` to be in-line with the API
=> feat!: Custom relationship type updates

src/types/mli-locations.d.ts
* ### Fix
Fixes a bug
Make the MLI location update body fields nullable. It is necessary to pass null for fields that were present and have been deleted.
* Fixes #
=> fix: MLI location update body nullable fields

src/endpoints/catalog.js, src/types/catalog.d.ts
* ### Feature
- Add `GetRelatedProducts` to `ShopperCatalog.Products` endpoint class.
- https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/paragon/team/-/issues/383
=> feat: Add GetRelatedProducts endpoint method to shopper catalog endpoint class

src/endpoints/multi-location-inventories.js
* ### Fix
Fixes a bug
I fixed the issue by updating `config.headers` directly instead of reassigning it. Reassigning created a new object, breaking the reference to the original `config`, which caused issues. The fix preserves the reference while adding the new header.
* Fixes #
=> fix: MLI endpoint header

src/endpoints/multi-location-inventories.js
* ### Fix
Fixes a bug
Fixed config.headers to ensure 'ep-inventories-multi-location' is scoped to MLI requests only.
* Fixes #
=> fix: isolate MLI header to prevent unintended propagation

src/types/order.d.ts
* ### Feature
- add new optional `promotion_source` field in order type
- [[MR-2671]](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/2671) Order page UI improvements
=> feat: add optional promotion source type in order

src/endpoints/user-authentication-password-profile.js, src/types/user-authentication-password-profile.d.ts, test/unit/user-authentication-password-profile.ts
* ### Fix
Fixes a bug
Token was incorrectly marked as required.
=> !fix: make AM auth token optional

src/endpoints/multi-location-inventories.js, src/types/multi-location-inventories.d.ts
* ### Feature
Completes coverage for Multi-Location Inventory feature.
Referenced Open API spec here https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/nebula/inventories.svc/-/blob/main/api/openapi.yaml
=> feat: complete MLI endpoints

src/utils/helpers.js, test/utils/helpers.ts
* ### Feature
- support `OR` in filter
- add new tests
- [[MR-2910] Status filter multi select](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/2910)
=> feat: support or in filter

.github/workflows/main.yml
* ### Chore
Changes to the build process or auxiliary tools and libraries such as documentation generation  
- bump actions/upload-artifact to v4
- https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> chore: bump actions/upload-artifact to v4

.github/workflows/main.yml
* ### Chore
Changes to the build process or auxiliary tools and libraries such as documentation generation  
- bump actions/download-artifact from v3 to v4
=> chore: bump actions/download-artifact from v3 to v4

src/types/accounts.d.ts
* ### Fix
Fixes a bug
- make legal name field in accounts optional 
[[MR-2949] Make legal name and registration id optional](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/2949)
=> fix: make legal name in accounts optional

.github/workflows/main.yml, src/types/cart.d.ts, src/types/order.d.ts
* ### Feature
* Add cart `snapshot_date` as an optional field
* Add order `order_number` as an optional field
Adds cart `snapshot_date` and order `order_number` fields to support further development.
Related to https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/3141.
=> fix: Add cart snapshot_date and order order_number option fields.

src/endpoints/customers.js, src/types/core.d.ts, src/types/customer.d.ts, src/utils/formatQueryString.js, src/utils/helpers.js
* ### Feature
- allow total_method param in customer endpoint
[[MR-3174] depends on this PR change ](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/3174)
=> feat: allow total_method param in customer endpoint

src/types/rule-promotions.ts
* ### Feature
- add support for auto_add and show_suggestions in rule promotion
- [[MT-21403] Add auto add & upsell suggestion in bxgy](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/3226)
=> feat: add support for auto add in rule promotion

src/endpoints/account-tags.js, src/endpoints/accounts.js, src/index.d.ts, src/index.js, src/types/account-tags.d.ts, src/types/accounts.d.ts
* ### Feature
- add account tags endpoints
- update accounts endpoints to support account tags in accounts
- add / delete account tags from an account
- support includes in the param
- [[MT-21428] Account tags](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/3253)
=> Feat: add support for account tags

src/endpoints/cart.js, src/types/cart.d.ts
* ### Feature
- support adding products and removing promotions from cart
[[MT-21773] Build and integrate the cart preview according to the new design](https://gitlab.elasticpath.com/commerce-cloud/commerce-manager/-/merge_requests/3320)
=> feat: support adding products and removing promotions from cart
